### ISSUE TITLE
窗口优化

### ISSUE THREAD

**Issue by hcwhan** [GameXG/TcpRoute2#16]
1.加个图标
2.加入通知栏(最小化到通知栏)
3.默认最小化启动

**Comment by hcwhan** [comment]
windows

**Comment by GameXG** [comment]
这个需要用.net 写个界面来实现。
golang 现在还不支持写界面。

**Comment by hcwhan** [comment]
好的 谢谢了 很好用
试了下 个人感觉比cow快些

**Comment by hcwhan** [comment]
给需要的人提供一个方法 无窗口后台启动
目录下新建一个vbs:
CreateObject("WScript.Shell").Run "cmd /c .\TcpRoute2.exe",0

**Comment by GameXG** [comment]
Windows GUI 界面完成。
