### ISSUE TITLE
对于 配置文件 的内容不太理解

### ISSUE THREAD

**Issue by laincat** [GameXG/TcpRoute2#17]
addr="127.0.0.1:7070"

[[UpStreams]]
Name="direct"
ProxyUrl="direct://0.0.0.0:0000"
DnsResolve=true

[[UpStreams]]
Name="SS1"
ProxyUrl="ss://method:passowd@123.123.123:5050"
DnsResolve=false

[[UpStreams]]
Name="SS2"
ProxyUrl="ss://method:passowd@123.123.123:5050"
DnsResolve=false

Credit=0

Sleep=80

CorrectDelay=50

=====

提问：

1.
对于 浏览器 有插件的，第一个 [[UpStreams]] ，direct（直连） 是不是可以不用保留了？
不过保留也没所谓，毕竟也许有些站也许能直连了，就更快了。。。

对吗？

再：
“ 直连 direct://0.0.0.0:0000/?LocalAddr=123.123.123.123:0 ”，后面这个 “?LocalAddr=123.123.123.123:0” 是啥意思？

2.
SS 不支持 TCP Fast Open ， One Time Auth ？

3.
“[[UpStreams]]” 这个 及 对应参数 需要 每一个代理地址 都写一遍？对吗？感觉怪怪的。。。(如上配置没错吧？)
（感觉有些繁琐。。。以后版本会作简化不？）

这样的格式会不会比较不好？

Proxy = direct, DnsResolve（需要的功能加上“,”隔开填上功能名，不启用的直接留空不写。）

Proxy = http, http://123.123.123.123:8088
Proxy = https, https://123.123.123.123:8088
Proxy = socks4, socks4://123.123.123.123:5050
Proxy = socks4a, socks4a://123.123.123.123:5050
Proxy = socks5, socks5://123.123.123.123:5050, upProxy=http://145.2.1.3:8080
Proxy = ss, ss://method:passowd@123.123.123:5050, TCPFastOpen, OneTimeAuth

这样如何，方便大量添加代理地址。。。

**Comment by laincat** [comment]
吐槽完，试玩去。。。

**Comment by GameXG** [comment]
1. 建议保保留，可能有的网站更适合直连的。
2. go 语言 TCP Fast Open 实现很麻烦，不计划支持。现在 ss 协议使用的 (ss-go)[https://github.com/shadowsocks/shadowsocks-go] 库，不支持 One Time Auth ，后期也许会写一个。
3. 主要是为了支持对当个代理配置参数，必须有 [[UpStreams]] 。不过除了 Proxy 之外都可以不写。


LocalAddr 是计划对于多线路自动选择最优线路而保留的功能，不过我没有多线环境无法测试。
程序会通过绑定指定的ip来访问网络，路由器能够识别到这个ip，根据ip分配到不同的线路。不过这个还没考虑好怎么做比较好。

**Comment by laincat** [comment]
好的，感谢。

**Comment by GameXG** [comment]
相关信息：

https://github.com/bradleyfalzon/tcp-fast-open

https://github.com/golang/go/issues/4842

**Comment by GameXG** [comment]
windows 不支持 TCP_Fast_Open  ...
https://en.wikipedia.org/wiki/TCP_Fast_Open
