### ISSUE TITLE
log_dir等参数无效

### ISSUE THREAD

**Issue by xuan880** [GameXG/TcpRoute2#20]
-log_dir无效，提示信息如下
➜  ~  tcproute -log_dir ~/tcproute.log -config ~/.tcproute/config.toml
flag provided but not defined: -log_dir
Usage of tcproute:
  -addr
        Change value of Addr. (default 127.0.0.1:7070)
  -config
        Change value of Config.
  -upstreams
        Change value of UpStreams. (default [{direct direct://0.0.0.0:0000 true 0 0 0} {shadowsocks ss://rc4-md5:xxxx@xxxxxxxxx:8080 false 3 100 50}])

Generated environment variables:
   SERVERCONFIG_ADDR
   SERVERCONFIG_UPSTREAMS
   SERVERCONFIG_CONFIG
很多参数都没有用。

**Comment by GameXG** [comment]
头疼，multiconfig 和 flag 冲突，需要考虑下怎么彻底解决了。

**Comment by GameXG** [comment]
f8a501c36bc21b42d6ed354c5c2eef71f985a1c8
multiconfig 不好用，而且意义不大，直接去掉了。glog 也移除了。
这些参数直接没有了...
