### ISSUE TITLE
没看懂啥是TCP路由

### ISSUE THREAD

**Issue by oxf1** [GameXG/TcpRoute2#22]
这个是一个squid一样的正向http、https,sockets代理服务器吗？

**Comment by GameXG** [comment]
是正向代理，会自动的选择最优的线路转发TCP请求。

**Comment by oxf1** [comment]
再问一下：我能够利用这个软件来搭建一个adsl代理服务码。
情况是这样的。我们开发一套爬虫，但是对方经常封锁。 现在我们需要部署http, https, socks5代理，出口使用多个运营商的adsl。
在应用程序端：例如我使用  123.222.22.22:8000 对应一条adsl物理线路， 123.222.22.22:8001对应另外一条物理adsl。
请问这个软件能做到吗？

**Comment by oxf1** [comment]
另外应用程序的某一个"任务“会请求一批url, 这些url必须从同一条物理adsl出去，也就是说在任务(或者看作是登录之后的session）期间必须绑定同一个adsl出口，不能换ip.

**Comment by GameXG** [comment]
不太明白你的意思。
单机播多个adsl还是那种专用的 vps一个vps带一个adsl？

单机播多个adsl 应该能通过 localAdde 绑定电信分配的 ip 来将多个adsl 作为多个线路区分出来。

// 直连 direct://0.0.0.0:0000//     可选参数： LocalAddr=0.0.0.0:0
表示tcp连接绑定的本地ip及端口，默认值 0.0.0.0:0。


>另外应用程序的某一个"任务“会请求一批url, 这些url必须从同一条物理adsl出去，也就是说在任务(或者看作是登录之后的session）
期间必须绑定同一个adsl出口，不能换ip.
这种需求只能内置到爬虫里面了，代理是不会知道什么时间切换线路的。

目前这个代理是为了普通上网需求使用的，策略是 upstream_tcpping.go
即什么线路最优用什么线路，不适合爬虫使用。你可以自己写个策略，例如 hash(客户端 ip +
目标地址)来实现特定客户端访问特定网站固定到一个线路。还是老问题，代理不知道你什么时间需要切换线路，所以切换线路功能必须是爬虫实现。

而且这个代理只对外提供 socks5 代理，不提供 http 代理，虽然http代理不考虑 websocket 之类的协议也不难。


狗剩 <notifications@github.com>于2016年1月3日周日 上午11:24写道：

**Comment by phpor** [comment]
作者很耐心，和bug无关的issue也能耐心解答，很赞
