### ISSUE TITLE
Connection reset 的判断问题

### ISSUE THREAD

**Issue by puteulanus** [GameXG/TcpRoute2#27]
比如 http://j.mp/pmx_installagent ，在我这里直接访问是这样的：
```bash
curl 'http://j.mp/pmx_installagent' -v
*   Trying 69.58.188.46...
* Connected to j.mp (69.58.188.46) port 80 (#0)
> GET /pmx_installagent HTTP/1.1
> Host: j.mp
> User-Agent: curl/7.43.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
貌似因为连接可以正常建立，TcpRoute2将它判断为了能正常访问，所以走了直连。

建议参考一下cow的设计：
>COW 将以下错误认为是墙在作怪：
>
>- 服务器连接被重置 (connection reset)
>- 创建连接超时
>- 服务器读操作超时
>
>无论是普通的 HTTP GET 等请求还是 CONNECT 请求，失败后 COW 都会自动重试请求。（如果已经有内容发送回 client 则不会重试而是直接断开连接。）
>
>用连接被重置来判断被墙通常来说比较可靠，超时则不可靠。COW 每隔半分钟会尝试估算合适的超时间隔，避免在网络连接差的情况下把直连网站由于超时也当成被墙。 COW 默认配置下检测到被墙后，过两分钟再次尝试直连也是为了避免误判。

顺便希望可以有一个指定某些网站走某一条线路的列表。应用场景包括无论如何都希望直连的网站（网易云音乐等）与登录验证中包含了IP信息的网站（某些VPS管理面板）。
前者即使因为本地网络环境波动造成使用代理打开较快，但不是国内IP无法正常播放的特性使打开速度没有意义。后者在多个二级代理的延迟排名变化造成IP变动时会要求重新登录，造成不便。

**Comment by GameXG** [comment]
http://j.mp/pmx_installagent  第二次访问还会失败吗？
设计时考虑到了这个问题，目前的策略是发现连接短时间断开并且未收到服务器返回的数据就标记故障，下次就不会在使用这个线路访问这个网站了。目前我这里实际使用的效果还不错，几天可能碰到一个页面打不开，刷新下就好了。
没有像 cow 那样静默重发数据的原因是 TcpRoute 是 socks5 代理，不涉及http协议，不清楚客户的请求是否是等幂的，所以不会重发数据。如果这个问题很频繁的话需要考虑增加http中间件来评估线路故障并重发请求了。

指定线路的功能我考虑下配置文件什么格式配置比较方便，有空就实现它。

**Comment by puteulanus** [comment]
之前的测试中是一直存在的，不过刚刚重新测试了下，发现已经走代理线路了。
我是在TcpRoute2的下面，使用Privoxy将sock5转换为http代理进行使用的，可能是Privoxy缓存了结果，造成一直无法连通的错觉。

十分感谢。

**Comment by GameXG** [comment]
问题解除。
使用socks5代理的话效果更好些，chrome预加载功能能提前建立到网站的连接，加快访问速度。

记一下故障日志，如果后期修改的话有个参考。
2016/01/04 20:38:14 为 j.mp:80 找到了最快的稳定连接 69.58.188.45:80 ，线路：direct.
2016/01/04 20:38:15 为 j.mp:80 找到了最快的稳定连接 69.58.188.45:80 ，线路：direct.
2016/01/04 20:38:15 协议处理错误：%!(EXTRA *errors.errorString=转发读错误：read tcp 192.168.1.83:60701->69.58.188.45:80: wsarecv: An existing connection was forcibly closed by the remote host.)
2016/01/04 20:38:15 协议处理错误：%!(EXTRA *errors.errorString=转发读错误：read tcp 192.168.1.83:60703->69.58.188.45:80: wsarecv: An existing connection was forcibly closed by the remote host.)
j.mp:80 的 direct 线路的尝试连接IP 69.58.188.45:80 ，由于ip属于经常故障ip，忽略本连接。
缓存命中：j.mp:80 代理：direct IP：69.58.188.46:80
2016/01/04 20:38:15 协议处理错误：%!(EXTRA *errors.errorString=转发读错误：read tcp 192.168.1.83:60707->69.58.188.46:80: wsarecv: An existing connection was forcibly closed by the remote host.)
j.mp:80 的 direct 线路的尝试连接IP 69.58.188.45:80 ，由于ip属于经常故障ip，忽略本连接。
缓存命中：j.mp:80 代理：direct IP：69.58.188.46:80
2016/01/04 20:38:16 协议处理错误：%!(EXTRA *errors.errorString=转发读错误：read tcp 192.168.1.83:60709->69.58.188.46:80: wsarecv: An existing connection was forcibly closed by the remote host.)
j.mp:80 的 direct 线路的尝试连接IP 69.58.188.45:80 ，由于ip属于经常故障ip，忽略本连接。
缓存命中：j.mp:80 代理：ss-vps IP：j.mp:80
