### ISSUE TITLE
TcpRoute2 是如何判断节点速度？只是 Ping？

### ISSUE THREAD

**Issue by laincat** [GameXG/TcpRoute2#31]
今天刚好有个节点挂了。然而它还是 一直选择 这个节点进行连接。。。。然后就一直没反应了。。。

**Comment by GameXG** [comment]
节点挂了？完全连接不上的那种？
目前的策略是同时建立直连及代理连接，哪个最先连接上就用哪个。
使用中访问网站出现链接重置时会标记错误，下次访问这个网站时会跳过这个故障的线路。

如果挂了连接不上应该不会使用的，我检查下吧。

**Comment by GameXG** [comment]
已经复现，涉及的协议是ss。当ss服务器开启，但是密码错误时会出现这个问题。
当ss可以连接上时，由于ss协议不会反馈是否登录成功，到目标网站是否建立连接成功，所以没有办法立刻检测到错误。只能通过请求情况来判断。

目前的策略是基于域名做的判断，造成每次访问一个新域名前两次都有可能被最快建立连接的并且密码错误的ss服务器坑。

解决方案有第一次添加ss时自动检测一次ss的正确性，另外增加线路级的判断，当发现线路多次错误时把整个线路标记错误，同时开启后台定时测试。

**Comment by GameXG** [comment]
v0.4.2 增加了一个线路级别的错误检测，实测效果良好。

**Comment by GameXG** [comment]
回退了这个修改。
由于存在严重的误判。当访问无法访问的网站时，将会造成所有线路都会误判。

需要更仔细的实现，更高的闸值使得判断网络错误比较慢，低的闸值会误杀。所以这个策略并不太好，还是需要使用 #5 http 中间件来做 http 重发。

**Comment by 85204** [comment]
可以参考花刺代理检查代理可用性，模拟访问特定网站，检查返回数据是否包含特定字符串
例如访问中文google，判断返回是否包含“手气不错”
很感谢作者写的这个软件，我一直在找COW的替代品，现在终于让我找到了，真的很好用!
顺便借楼问一下，我还是需要转换成http代理来方便一些软件使用，有没有比privoxy转化效率更高的软件，现在还是有些卡网，谢谢

**Comment by ruiruige** [comment]
@85204   polipo也能转换成http代理，问题是我觉得，有可能比privoxy占用率还高
