### ISSUE TITLE
每次打开都来句 “发现异常IP： map[]”

### ISSUE THREAD

**Issue by laincat** [GameXG/TcpRoute2#38]
这是什么鬼。。。都还没开网页啊。。。

**Comment by GameXG** [comment]
好吧，看样我需要修改下提示语。

这个本意是输出 域名纠错 的 ip。
TcpRoute 会定时检查是否存在域名纠错、dns劫持之类的情况，如果发现了会将相关ip加入黑名单。

**Comment by GameXG** [comment]
v0.5.0 发布已纠正这个问题。
