### ISSUE TITLE
TcpRoute2 只监听在 IPv4 上，开启 DNS 纠错功能也会返回 IPv6 的地址

### ISSUE THREAD

**Issue by rampageX** [GameXG/TcpRoute2#48]
当设置 TcpRoute2 的监听地址为 0.0.0.0 时，此时实际上 TcpRoute2 会监听在 ::: 这个 IPv6 的地址上，如果此时开启 dns 纠错功能，会返回一些 IPv6 的地址，如：

`tcp        0      0 :::7373                 :::*                    LISTEN      20582/TcpRoute2-lin`

`为 scontent-hkg3-1.xx.fbcdn.net:443 找到了最快的稳定连接 [2a03:2880:f002:110:face:b00c:0:3]:443 ，线路：[UNIQUE-HK]`

而实际上代理是不支持 IPv6 连接的，这样会导致很长时间都打不开目标网站。

即使强制它只监听在 127.0.0.1 这样的地址上，仍然会返回 IPv6的地址：

`为 gp3.googleusercontent.com:443 找到了最快的稳定连接 [2404:6800:4005:802::2001]:443 ，线路：[GY-HK1].`

1. 能否区分下 0.0.0.0 和 ::: 这两种监听地址？或是增加一个全局的 IPv6 开关？
2. 能否在监听 IPv4 地址，同时开启 dns 纠错时，不返回 IPv6 的解析结果？

**Comment by GameXG** [comment]
问题出在 DnsResolve 选项，直连线路应该设置为 true，代理线路建议设置为 false。
true 时表示使用 TcpRoute dns 解析，false 时表示使用远端 DNS 解析。

**Comment by GameXG** [comment]
对代理线路开启 DnsResolve 意味着不再使用远端dns解析，可能会造成各种奇怪的问题。

文档真的需要重写了，好多都没描述清楚。

**Comment by rampageX** [comment]
@GameXG 按照您说的重新设置OK了；

那么按照您的描述，其实 DnsResolve 改成 LocalResolve 要合适一些。

**Comment by GameXG** [comment]
是的，但是参数已经公开了，很难再修改了。
