### ISSUE TITLE
关于配置文件的问题。

### ISSUE THREAD

**Issue by laincat** [GameXG/TcpRoute2#50]
[[UpStreams]] 和 [[Hosts]] 有多条线路，多个 hosts 的话。除了链接本身必须填写外。

其它参数 也必须都重复填写吗？

例如是这样？
```
[[UpStreams]]
Name="proxy 1"
ProxyUrl="socks5://1.1.1.1:5050"
Credit=0
Sleep=80
CorrectDelay=0
[[UpStreams]]
Name="proxy 2"
ProxyUrl="socks5://2.2.2.2:5050"
Credit=0
Sleep=80
CorrectDelay=0
```

还是这样？
```
[[UpStreams]]
Name="proxy 1"
ProxyUrl="socks5://1.1.1.1:5050"
[[UpStreams]]
Name="proxy 2"
ProxyUrl="socks5://2.2.2.2:5050"

Credit=0
Sleep=80
CorrectDelay=0
```

**Comment by GameXG** [comment]
必须这样：
[[UpStreams]]
Name="proxy 1"
ProxyUrl="socks5://1.1.1.1:5050"
Credit=0
Sleep=80
CorrectDelay=0
[[UpStreams]]
Name="proxy 2"
ProxyUrl="socks5://2.2.2.2:5050"
Credit=0
Sleep=80
CorrectDelay=0

不过大部分参数都有默认值，所以最短的话这样就可以：

[[UpStreams]]
ProxyUrl="socks5://1.1.1.1:5050"
Sleep=80
[[UpStreams]]
ProxyUrl="socks5://2.2.2.2:5050"
Sleep=80

**Comment by GameXG** [comment]
对了，低于 v0.5.4 会有部分参数默认值有问题。

**Comment by laincat** [comment]
好的，感谢。
