### ISSUE TITLE
Linux 版本可否原生支持 Daemon 模式

### ISSUE THREAD

**Issue by rampageX** [GameXG/TcpRoute2#52]
我知道可以用 nohup 等方法实现，但是还是希望能原生支持后台运行。

**Comment by GameXG** [comment]
感觉使用 supervisord 之类的做服务管理更好些。
不过这个功能不麻烦，有空加上。

**Comment by laincat** [comment]
Linux 新手，不懂如何让 系统全局使用 TcpRoute2。是需要其他的软件么？求全攻略。。。(真的很新的新手)

**Comment by qianlifeng** [comment]
@laincat 使用 Proxifier
