### ISSUE TITLE
5.0升到5.8之后大量无法访问的网站被交给了直连

### ISSUE THREAD

**Issue by puteulanus** [GameXG/TcpRoute2#56]
背景：
本地运营商有DNS劫持，并且所有不存在域名都会被返回搜狗搜索的IP。
内网设备上有TCP查询的防污染DNS，本机、路由器的DNS服务器均设置的是那台内网设备的IP地址。
运行环境的系统设置DNS指向的是它本机，在CMD中nslookup可以看到正确结果。
症状：
从5.0升级到5.8之后，大量网页无法打开，log显示包括各种谷歌域名在内的各种请求全部选择了直连，同时出现了大量试图连接故障IP的信息。

因为所有的东西现在都是跑在一台XP上，调试很麻烦。大致的猜测是在判断线路时发生了DNS污染，导致原本无法连接的请求的IP被运营商污染成了搜狗的，结果请求全部分配给了直连。但是本机、运行环境以及网关的DNS设置均指向的是抗污染的自建DNS，这个污染发生在哪里非常迷。。退回5.0之后症状消失。

**Comment by GameXG** [comment]
可以提供日志及配置文件吗？目前的信息无法判断出现问题的具体原因。

>日志显示是“由于线路属于经常故障线路，忽略本连接”还是“由于ip属于经常故障ip，忽略本连接” ？
如果是线路故障那么需要检查代理线路是否正常，ss密码错误很容易出现线路故障无法上网的问题。少量 ip 故障不需要在意，tcproute会尝试同时连接多个ip，少量有故障不影响使用。

>无法打开的页面是直接无法打开还是显示域名纠错页面或ssl证书错误？
tcproute自带屏蔽dns纠错功能，会定时dns查询不存还在的域名，将查询获得的纠错ip放入黑名单。

**Comment by puteulanus** [comment]
日志：
```
2016/03/12 13:14:59 为 www.youtube.com:443 找到了最快的稳定连接 74.125.203.101:4
43 ，线路：SG-CN.
2016/03/12 13:15:00 为 mtalk.google.com:443 找到了最快的稳定连接 64.233.189.188:
443 ，线路：direct.
2016/03/12 13:15:00 为 r5---sn-npo7zn7d.googlevideo.com:443 找到了最快的稳定连接
 74.125.171.203:443 ，线路：SG-CN.
2016/03/12 13:15:01 为 r5---sn-npo7zn7d.googlevideo.com:443 找到了最快的稳定连接
 74.125.171.203:443 ，线路：SG-HK.
2016/03/12 13:15:01 为 r5---sn-npo7zn7d.googlevideo.com:443 找到了最快的稳定连接
 74.125.171.203:443 ，线路：SG-HK.
2016/03/12 13:15:01 为 r5---sn-npo7zn7d.googlevideo.com:443 找到了最快的稳定连接
 74.125.171.203:443 ，线路：SG-HK.
2016/03/12 13:15:01 为 r5---sn-npo7zn7d.googlevideo.com:443 找到了最快的稳定连接
 74.125.171.203:443 ，线路：SG-HK.
2016/03/12 13:15:01 为 r5---sn-npo7zn7d.googlevideo.com:443 找到了最快的稳定连接
 74.125.171.203:443 ，线路：SG-HK.
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-CN 线路的尝试连接IP 74.125.171.203:44
3 ，由于ip属于经常故障ip，忽略本连接。
r5---sn-npo7zn7d.googlevideo.com:443 的 SG-HK 线路的尝试连接IP 74.125.171.203:44
3 ，由于线路属于经常故障线路，忽略本连接。
```
配置文件：
```
addr="127.0.0.1:7070"
PreHttpPorts=[0,]
PreHttpsPorts=[0,]

[[UpStreams]]
Name="direct"
ProxyUrl="direct://0.0.0.0:0000"
DnsResolve=true
[[UpStreams.Whitelist]]
Path="direct/whitelist.txt"
UpdateInterval="24h"
Type="suffix"
[[UpStreams.Blacklist]]
Path="direct/blacklist.txt"
UpdateInterval="24h"
Type="suffix"

[[UpStreams]]
Name="SG-HK"
ProxyUrl="socks5://127.0.0.1:1081"
DnsResolve=true
Credit=0
Sleep=80
[[UpStreams.Whitelist]]
Path="sg-hk/whitelist.txt"
UpdateInterval="24h"
Type="suffix"
[[UpStreams.Blacklist]]
Path="sg-hk/blacklist.txt"
UpdateInterval="24h"
Type="suffix"

[[UpStreams]]
Name="SG-CN"
ProxyUrl="socks5://127.0.0.1:1082"
DnsResolve=true
Credit=0
Sleep=80
[[UpStreams.Whitelist]]
Path="sg-cn/whitelist.txt"
UpdateInterval="24h"
Type="suffix"
[[UpStreams.Blacklist]]
Path="sg-cn/blacklist.txt"
UpdateInterval="24h"
Type="suffix"

[[Hosts]]
Path="hosts.txt"
Type="base"

[[Hosts]]
Path="http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
Type="base"
UpdateInterval="24h"
```

**Comment by GameXG** [comment]
将代理线路的 DnsResolve=true 参数去掉试一下。

DnsResolve=true 意思是执行本地dns解析，只建议直连线路设置，代理设置会使得代理无法进行远端dns解析。

目前看日志情况像是代理线路报告已建立到目标网站的连接，但是实际发送https请求时却断开了连接，所以被tcproute标记了线路故障。

如果去掉dns参数还是有故障，需要增加详细日志查看原因了。

**Comment by puteulanus** [comment]
运行环境的XP装有Pcap_DNSProxy，本地连接的DNS指向的是XP它自己的内网地址，路由器（网关）的DNS也是指向的它，所以无论是在上边指向 nslookup www.google.com 还是 nslookup www.google.com 192.168.1.1 得到的都是正确结果。

这样设置的本意是在确保DNS没有污染了的情况下尽量使用本地缓存减小消耗的时间。

在命令行直接执行 telnet mtalk.google.com 443 是无法建立连接的，所以我才感觉比较迷。程序选择了直连线路，也就是说程序在执行本地解析这个操作时，得到的IP地址和默认DNS给出的不同，是一个可连接的地址。

**Comment by puteulanus** [comment]
运行环境的配置如图
![9a452b8e-e32e-461c-bd67-3cc5eeed8c88](https://cloud.githubusercontent.com/assets/4849177/13722349/67eb13e2-e87d-11e5-9c57-e761498a1309.png)

**Comment by laincat** [comment]
@puteulanus 的 [[UpStreams.Blacklist]] ?这个是不是用错了？

。。。。。。。。

不是应该这样用吗？

当 Direct 下 [[UpStreams.Whitelist]] 就是 “白名单” whitelist.txt。

当 Proxy 下 [[UpStreams.Whitelist]] 就是 “黑名单” blacklist.txt。

**Comment by laincat** [comment]
头大=。 =好像没错。

TcpRoute2 判断是否直连 好蛋疼，经常误判，造成浏览体验不佳。。。

=-
题外问题：
https 的 “线路的信誉度” 看 “https://github.com/GameXG/TcpRoute2/blob/master/netchan/dialchan_filter.go#L19” 是设置 “-500” 然而并不能用，看来是 商家并没有加密？

-------------
目前的配置文件：

```
addr=":7070"

[[UpStreams]]
Name="direct"
ProxyUrl="direct://0.0.0.0:0000"
DnsResolve=true
sleep=0
[[UpStreams.Whitelist]]
Path="https://raw.githubusercontent.com/GameXG/TcpRoute2/master/direct.txt"
UpdateInterval="24h"
Type="suffix"

[[UpStreams]]
Name="SSLedge JP"
ProxyUrl="https://和谐?standardheader=true&insecureskipverify=true"
DnsResolve=false
Credit=**-500**
Sleep=80
[[UpStreams.Whitelist]]
Path="https://raw.githubusercontent.com/renzhn/MEOW/master/doc/sample-config/proxy"
UpdateInterval="24h"
Type="suffix"
```

**Comment by laincat** [comment]
头大=。 =好像没错。

TcpRoute2 判断是否直连 好蛋疼，经常误判，造成浏览体验不佳。。。

=-
题外问题：
https 的 “线路的信誉度” 看 “https://github.com/GameXG/TcpRoute2/blob/master/netchan/dialchan_filter.go#L19” 是设置 “-500” 然而并不能用，看来是 商家并没有加密？

-------------
目前的配置文件：

```
addr=":7070"

[[UpStreams]]
Name="direct"
ProxyUrl="direct://0.0.0.0:0000"
DnsResolve=true
sleep=0
[[UpStreams.Whitelist]]
Path="https://raw.githubusercontent.com/GameXG/TcpRoute2/master/direct.txt"
UpdateInterval="24h"
Type="suffix"

[[UpStreams]]
Name="SSLedge JP"
ProxyUrl="https://和谐?standardheader=true&insecureskipverify=true"
DnsResolve=false
Credit=**-500**
Sleep=80
[[UpStreams.Whitelist]]
Path="https://raw.githubusercontent.com/renzhn/MEOW/master/doc/sample-config/proxy"
UpdateInterval="24h"
Type="suffix"
```

**Comment by puteulanus** [comment]
@laincat 之前的文档的确是有Blacklist这个东西，我是参考 https://github.com/GameXG/TcpRoute2/commit/ea6529e817093f3d65d4bb3daf15842acd95c7b4 写的配置，看来新版是取消掉了。

5.8在读配置的时候两个Blacklist似乎的确会报错，不过除了Direct的Whitelist以为，其他的文件内容全部为空，应该不会影响到线路的选择。

话说其实我感觉直连的黑名单比代理的黑白名单更有用一些。单从逻辑上讲，把希望走代理的网站加入直连黑名单中是可以保留线路选择与故障转移等特性的，而加入某一代理的白名单的话至少线路选择的作用是消失掉了，比如SL香港这种偶尔被攻击延迟能上400的，一旦抽了就可能影响到它下面白名单里边的网站的访问。

当然代理的黑白名单也是有作用的，比如舰娘这种必需固定走某条代理，或者某网站被拉了黑名单需要单独避开某一代理的IP的情况。

**Comment by GameXG** [comment]
抱歉，黑名单没有取消，是文档写错了，黑名单是 [[UpStreams.Blacklist]] 。

@laincat  线路信誉度的目的是当使用第三方代理时，觉得代理可能不安全，这时候设置较低的信誉度，那么一些不安全的明文协议(http等)将不会通过这个代理转发。

https://github.com/GameXG/TcpRoute2/blob/master/netchan/dialchan_filter.go#L19%E2%80%9D
80:0 意思是http协议(80)端口只会通过信誉大于等于0的代理转发，信誉低于0的代理不会转发http协议。

Credit=**-500** 意味着这个代理只能转发 https、smtp ssl、imap ssl、pop ssl 等类型的请求，http类型的请求由于代理信誉度过低不会进行转发。

**Comment by laincat** [comment]
好的，总算把配置理解差不多了。。。。Orz

**Comment by GameXG** [comment]
@puteulanus  可以试一下 v0.5.9 ，为转发错误增加更详细的日志。

也可以试一试下面的命令测试下代理服务器
1.exe -proxy=127.0.0.1:7070

[1.zip](https://github.com/GameXG/TcpRoute2/files/180648/1.zip)
