### ISSUE TITLE
节点速度竞争与 blogspot 类网站有冲突

### ISSUE THREAD

**Issue by rampageX** [GameXG/TcpRoute2#57]
背景：
xxx.blogspot.com 上面的博客会根据访问 IP 来源改变域名后缀，比如是香港 IP 就变成 xxx.blogspot.hk，日本就变成 xxx.blogspot.jp。
我的 TcpRoute2 配置文件中有 HK, JP, SG 等各地服务器；

问题：
大多数情况下并无问题，但是最近发现好几次很长时间打不开此类页面，Chrome 的连接信息栏显示地址不停在 hk 和 jp 两个后缀的域名间切换。

是否是 TcpRoute2 的代理速度优化功能，和这些网站自动切换（就近）域名的功能发生了冲突？

版本是最新 5.8。

**Comment by GameXG** [comment]
在两个线路速度相近，并且网络不断波动时会出现代理切换的问题。

可以尝试给香港线路增加 blogspot.hk ，日本线路增加 jp 白名单解决。

# suffix 后缀匹配。即 abc.com 匹配 abc.com、www.abc.com、aaa.www.abc.com，不匹配 aaaabc.com。

**Comment by rampageX** [comment]
谢谢，我试试
