### ISSUE TITLE
SS方式密码含"%"导致配置出错

### ISSUE THREAD

**Issue by arsonloupeen** [GameXG/TcpRoute2#61]
ProxyUrl="ss://ss加密方式:ss代理密码@ss服务器地址:端口"

SS方式密码含"%"导致配置出错

**Comment by GameXG** [comment]
为了能够支持:@ 之类的符号，这里用的是标准的uri格式，所以特殊符号需要转义。
例如 % 需要写成 %25 。

想知道转义后的格式最简单的办法是将特出符号输入搜索引擎输入框点击搜索，url里面就是转义后的内容。

**Comment by arsonloupeen** [comment]
谢谢，已解决。

**Comment by arsonloupeen** [comment]
谢谢，已解决。
