### ISSUE TITLE
永远不会直连 和 下线的socks5代理长时间影响连通性 和 GoAgent支持

### ISSUE THREAD

**Issue by wfjsw** [GameXG/TcpRoute2#62]
问题1：永远不会直连
- 前提：配置过 `direct` (Credit>0)，继承了COW的黑白名单， 白名单(suffix)里有 `.cn` 别的都是纯Upstream
- 测试地址： `http://ip.cn`
- 路由结果：走了个台湾的shadowsocks出去

问题2：下线的socks5代理长时间影响连通性
- 情景1：有一个速度比较快的socks5上游突然挂了
- 症候：当时访问的走这个代理的网站在N分钟之内继续缓存到这个代理导致一直连不上 直到这个线路被标记为经常故障线路
- 情景2：socks5对应的shadowsocks服务器集体更新
- 症候：所有线路变成经常故障线路持续N分钟 被迫重启路由器

问题3：走HTTP上游代理时日志里没有任何体现
- 大概没什么多说的吧...

问题4：配合使用GoAgent的时候报错
- 前提：加了允许不正常证书的flag
- 报错： `错误：TLS 协议握手错误：tls: oversized record received with length 20527`

问题5：日志里出现大量没被替换的占位符
- 例子： `%v %v(%v):%v dialCreadit=%v ipCredit=%v 信任度低，拒绝访问。 tcp [censored-host] [censored-host] [censored-port] -1 -1`

**Comment by GameXG** [comment]
问题1： 猜测配置错误，请提供配置文件。

问题2：

* 情景1   当使用上次缓存的地址时会根据上次连接建立时间来配置连接超时时间，如果超时后会执行全代理测速。这种策略一般情况下不会出现问题，但是有些socks5代理不遵守socks5协议(例如 ss )，在为建立到目标网站连接时就会返回连接建立成功的信息，造成这个策略失败。看代理被标记为“经常故障线路”那么应该是这个情况。
* 情景2 和1一样，这个是同一个问题。有计划实现http中间件的方式来实现更准确的状态测试，但是目前没时间完成。

问题3 ： 不清楚意思，所有代理都是通过统一接口提供的，如果没有日志那么应该是没选择使用http代理。实际由于协议实现，ss 不返回是否已经成功建立了到目标网站的连接，所以目前到ss服务器的连接建立成功后就当作已经建立了到目标网站的连接，ss测速会显得比http代理快，很容易使得http代理没机会使用。

问题4： 这个需要试一下了，我没用过 GoAgent 。

问题5： 我跑一下 vet 把他们找出来。

**Comment by wfjsw** [comment]
问题1：回家上传日志
问题2：这样...
问题3：我在lantern日志里看到了连接成功提示 但在router日志里没看到导向到lantern的 不过这样说的话大概正在测试线路
问题4：GoAgent有伪装证书玄学 至今没看懂那个代理方式 不过大概是标准HTTP（非CONNECT）然后挂了个SSL
问题5：等待升级

**Comment by wfjsw** [comment]
配置文件：
https://ipfs.io/ipfs/QmQ9KBpcsqdNbW6d9xYcw9q8P2KRrBtkr4nCWXmspLxHfB

**Comment by GameXG** [comment]
```
# [[UpStreams.Whitelist]]
# Path="/home/jsw/.cow/direct"
# Type="suffix"
```

白名单没启用...

另外建议使用内置的ss程序，已知 C# ss 程序会在收到请求后立刻回复连接建立成功，而不是实际建立连接后回复链接建立成功，使得测速完全失败。根据ss协议，感觉其他ss也会是类似的情况。

**Comment by wfjsw** [comment]
白名单是后来发现没用然后禁用掉的

**Comment by GameXG** [comment]
好吧，我自己都忘记了后缀匹配规则了....
后缀匹配内部做了特殊的处理，想匹配 *.cn 的域名，直接输入 cn 即可，前面不能加点 。
软件会自动处理， cn 不会匹配 abc.acn ， 只会匹配 cn 、abc.cn 、000.abc.cn 等情况。

**Comment by wfjsw** [comment]
🌚👍🏿
