### ISSUE TITLE
请求内置HTTP Proxy Server

### ISSUE THREAD

**Issue by septs** [GameXG/TcpRoute2#65]
see https://github.com/mischief/http2socks/blob/master/main.go

**Comment by GameXG** [comment]
好的 http 代理实现起来很麻烦，上面那个实现不支持  websocket 。
完善的 http 代理不是短时间能够完成的，目前没有时间做。

**Comment by septs** [comment]
可以试试我实现的 HTTP Proxy Server
see https://github.com/RouterScript/HTTPProxy
