### ISSUE TITLE
TcpRoute2开放的代理 支持账号密码认证吗

### ISSUE THREAD

**Issue by ruiruige** [GameXG/TcpRoute2#71]
也就是默认的7070

**Comment by GameXG** [comment]
是的，这个不支持用户名密码验证。


ruiruige <notifications@github.com>于2016年10月15日周六 下午6:04写道：

**Comment by ruiruige** [comment]
@GameXG  我不太懂HTTP协议哈，我可以为它上层在包装一个代理，在那里面做简单认证，比如：
privoxy   polipo  squid  甚至windows的CCproxy什么估计都可以  （这几种估计都支持sock5 二级代理）

我的问题是：
在linux环境下 用什么比较合适呢？  我担心比如某个服务器不支持websocket  或者不支持其他的 ，我希望我用的服务器不成为TcpRoute2的 短板

**Comment by ruiruige** [comment]
@GameXG  还有个问题：
![image](https://cloud.githubusercontent.com/assets/8370100/19411448/ae1a6626-9334-11e6-9cf7-b39fc6c089e7.png)

为什么我配置了
PreHttpPorts=[80,]
PreHttpsPorts=[443,]

还是说我未指定DNS纠错啊？

最后就是我在哪里配置我的 DNS服务器呢？ 能否支持多个DNS呢？
难道是继承系统的 /etc/resolv.conf ？

**Comment by GameXG** [comment]
之前没考虑 tcproute作为公开的代理，所以没有验证功能。最近写了好多次socks5协议解析，抽时间加上这个功能。
那几种我也没没测试过对于 websocket 是否支持。

有些地方浏览器打开不存在的域名会被isp导航到纠错页面(广告页面)，dns纠错屏蔽功能就是处理这个的，这个功能会屏蔽掉纠错服务器的ip。
dns目前只是使用系统默认dns，虽然开发分支有一个允许自定义dns的实现，不过最近忙，未完成配置文件之类的东西。

ruiruige <notifications@github.com>于2016年10月16日周日 上午12:10写道：
