### ISSUE TITLE
2个建议

### ISSUE THREAD

**Issue by ruiruige** [GameXG/TcpRoute2#73]
1. 今天发现百度走了国外VPS不是代理  
   定位半天 以为是TCP 性能问题 ，最后发现是装了dnsmasq 把我的/etc/resolv.conf 改成127.0.0.1了
   （我自己活该，没设置永久DNS）

建议：启动时，如果判断开启本地直接时，可以输出一下DNS
1. 建议添加本地直连白名单
   hdslb.com  
   aixifan.com    （前两个好像是a b 站测速用的）

alicdn.com      （貌似alicdn  已经取代taobaocdn了  ）
sina.com
sina.com.cn
加入直连whitelist

**Comment by GameXG** [comment]
目前dns是直接使用的系统dns，程序并不清楚具体的dns服务器地址。
允许手工指定dns的版本还在开发分支，未完成配置部分。

直连站点已经加入。
