### ISSUE TITLE
关于谷歌机器人判断-

### ISSUE THREAD

**Issue by ruiruige** [GameXG/TcpRoute2#75]
![image](https://cloud.githubusercontent.com/assets/8370100/20389417/7d8e2616-ad04-11e6-880b-d340afa43fbd.png)

请问这个跟它有关吗？ 大家用的时候有没有遇到过这个问题？
感觉像是不停地访问谷歌，然后谷歌觉得我是机器人，一天要验证七八次

**Comment by GameXG** [comment]
直连线路会根据dns解析得到的多个ip尝试同时建立连接，
但是在默认情况(DnsResolve=false)下每个代理只会建立一个到网站的连接，15分钟内会使用缓存的最快线路。
所以以除非能够直连google，否则不会建立很多连接。

这种情况一般是vps所在机房有人大量访问google，do的旧金山机房经常这样。
