### ISSUE TITLE
关于远端DNS解析的疑问和建议

### ISSUE THREAD

**Issue by ruiruige** [GameXG/TcpRoute2#79]
建议：
> chrome 默认是远端dns解析，当不使用 redsocks、Proxifier 时不需要这个功能。

是否能够改成：
>  在代理模式下，chrome 默认是远端dns解析，当不使用 redsocks、Proxifier 时不需要这个功能。

疑问：
    在远端代理线路下，`PreHttpPorts` 和 `PreHttpsPorts` 这两个配置项 和 `DnsResolve`有什么关系？
    还就是`TcpRoute 接收到目的地址是域名的请求将不执行客户端dns解析纠正功能` , 如何让它接受到目的地址是域名的时候，也走远端DNS解析呢？
    判断目的地址是域名还是IP的方法是什么？是根据是否存在host头和SNI 字段来判断的吗

问题有点多 希望不要嫌我麻烦哈

**Comment by GameXG** [comment]
DnsResolve 其实应该写成本地dns解析，这个是线路级别的设置，只对配置的线路生效。true 表示这个线路不使用远程dns解析。目的是当设置为true时会对本地解析得到的多个ip地址同时建立连接来选择最快的ip。非本地线路不建议设置这个。

浏览器-----> PreHttpPorts 和 PreHttpsPorts 模块 --> 线路选择器 --->多个线路。

PreHttpPorts 和 PreHttpsPorts 只是针对浏览器不支持远程dns时的一个补救措施，当tcproute收到的socks5请求目标地址是域名时会读取 http头的host字段货SNI来获得目标网站域名，然后修改socks5请求，将ip换成域名，之后转发给多个线路。如果某个线路设置了 DnsResolve=true，那么这个线路会执行本地dns解析获得多个ip然后同时连接这多个ip。如果线路未设置 DnsResolve=true ，那么将执行远程dns解析。

如果未开启 PreHttpPorts 和 PreHttpsPorts ,并且浏览器不支持远程dns解析，那么线路模块收到的将是ip，不管线路时本地还是远程dns解析都没用了，因为根本没有域名可以提供解析...
