### ISSUE TITLE
关于强制代理服务器DNS解析

### ISSUE THREAD

**Issue by ruiruige** [GameXG/TcpRoute2#81]
2017/03/22 19:24:15 [强制代理服务器DNS解析] 对目的地址是 180.149.153.11:80 的请求进行了重定向，新目标：rm.api.weibo.com:80

我明明在直连线路中添加了weibo.com ，具体见https://github.com/ruiruige/china-direct/blob/master/white.txt，模式是suffix
为啥它还是会有强制代理服务器DNS解析呢

**Comment by GameXG** [comment]
这个强制代理dns解析时在线路选择前面做的，这时还未经过白名单。

可以通过配置关闭强制代理dns解析。
但是请注意，看日志，你的浏览器提供给 tcproute 的地址都是ip，也就是浏览器没开远程dns解析，如果再把这个强制dns解析功能关闭，那么会造成所有dns都是本地解析了，通过代理访问时可能会出现缓慢的问题。
