### ISSUE TITLE
使用UDP模拟TCP完成Shadowsocks的链路测试。

### ISSUE THREAD

**Issue by wdhwg001** [GameXG/TcpRoute2#87]
不是完全使用UDP模拟一个TCP，而是仅仅使用Shadowsocks的UDP转发发送一个SYN，等待Shadowsocks传回SYN/ACK后，随即立刻RST掉，记录延迟，后期如被选中则使用正常的TCP进行通讯。

似乎比起Patch客户端来说更靠谱一点，获得的数据也是更真实的，改善Shadowsocks协议的TCP Ping会相当程度的提升工具的可用性。

**Comment by wdhwg001** [comment]
看了一下，似乎https://github.com/RouterScript/ProxyClient 这里的Shadowsocks实现是包含了UDP支持的。

ProxyClient或许可以考虑使用那边的实现。

**Comment by GameXG** [comment]
udp 无法转发 tcp 的 syn 包。

现在的版本不需要patch客户端，内置了 ss 客户端，延迟计算是按照到 ss 服务器的时间+修正时间计算的，虽然不如直接计算到网站的时间，但是也差不多了。
另外 ss 协议部分在文档内被删除了，可以看上一提交。
