### ISSUE TITLE
这份源码可以编译openwrt版本吗？

### ISSUE THREAD

**Issue by fregie** [GameXG/TcpRoute2#91]
tcproute似乎在路由器上能发挥更大的作用

**Comment by cjjdaq** [comment]
下载了TcpRoute2-linux-amd64.zip在openwrt x64上无法运行

**Comment by GameXG** [comment]
没测试过，应该可以。

**Comment by yiguihai** [comment]
可以的我的K3用上去网速很快，以前小鸡vps垃圾即使忽略中国ip段也是很慢，现在用了这个能直连的直连不能直连的才用代理。还无视dns污染。就差透明代理了。简直就是神器！

**Comment by luoyanghero** [comment]
> 可以的我的K3用上去网速很快，以前小鸡vps垃圾即使忽略中国ip段也是很慢，现在用了这个能直连的直连不能直连的才用代理。还无视dns污染。就差透明代理了。简直就是神器！

这个工具只是用来提升网速的吗?如下场景能否使用：
局域网里的电脑a,b,c,...使用代理，都通过电脑AA上公网。
现在AA电脑有一些限制，不允许一些APP（APP1,APP2,...)上网，其他APP允许上网。
作为电脑b，能否在b上面装一些工具或者进行些设置（不在AA上设置和安装工具），让APP1,APP2，像其他APP一样，也能上网。
