### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by yiguihai** [GameXG/TcpRoute2#96]
这个程序用了几个月了，这些是我的个人使用感受
首先是优点：

无视dns污染强制dns解析
支持多种代理方式
可以做到撞墙时从直连切换到翻墙代理

缺点：
不支持透明代理需要另外的程序转换成socks5
不支持udp

改进建议：
支持透明代理这样就不用redsocks转换了

增加一个dns监听处理的功能。因为有些污染会返回127.0.0.1的地址，例如 jav321.com 这种的话强制dns也没有用

去除一些无用功能 ss协议、hosts。我先前以为hosts是屏蔽域名用的，测试后才发现是作用在代理中的而且功能不是屏蔽域名而是禁止某个域名使用这一个代理。还有这个ss协议太过鸡肋，不支持aead和插件建议剔除减小体积

增加一个分流功能某个或某组域名只能使用指定的代理

望采纳

**Comment by GameXG** [comment]
>增加一个功能某个或某组域名只能使用指定的代理，这样可以破ip版权验证的问题

这个可以直接使用指定代理白名单（ UpStreams.Whitelist ） ，可以支持泛域名、正则表达式。


目前工作繁忙，暂时时没时间增加新功能，只能等工作轻松时才能去操作了。

>

**Comment by yiguihai** [comment]
> 增加一个功能某个或某组域名只能使用指定的代理，这样可以破ip版权验证的问题
> 这个可以直接使用指定代理白名单（ UpStreams.Whitelist ） ，可以支持泛域名、正则表达式。
> 
> 
> 目前工作繁忙，暂时时没时间增加新功能，只能等工作轻松时才能去操作了。
> …

但是其它域名也会走这个代理，难道要添加一个黑名单写*来匹配？

**Comment by GameXG** [comment]
意思是，這個代理只允許走指定的几个域名？
那么的确需要添加 * 到黑名单。

yiguihai <notifications@github.com> 于2020年6月13日周六 上午12:06写道：
